XRT 2749 feat: Add in iot_data_iter_size function
IOTechSystems/iotech-c-utils pull request #324
Opened 2024-01-16 17:39 UTC by luke-shields

Functionality required for alternative approach to bug fix https://github.com/IOTechSystems/xrt/pull/1791 whereby XRT crashes on attempted transform of rebirth_json. This function would then be used to make the sparkplug transforms accept both lists and vectors for complex data types. 

Happy to discuss if this is the right approach as I realise slightly odd to be getting the 'size' of an iterator.

2024-01-17 05:26 UTC, dpazj reviewed
LGTM. IMO renaming `iot_data_iter_size` to `iot_data_iter_length` would make more sense

2024-01-17 12:13 UTC, SteveOss requested changes
The CU_ASSERT macros do not need a terminating semi-colon (CLion should be flagging this). Also need space before function/macro brace "(".

2024-01-17 12:16 UTC, luke-shields commented
@dpazj @SteveOss Changes made

2024-01-17 15:05 UTC, SteveOss requested changes
Need to support BINARY type as well

2024-01-17 16:12 UTC, luke-shields commented
@SteveOss added binary support

2024-01-17 16:22 UTC, SteveOss commented
@dpazj @edward-scott @luke-shields Might be an argument for this function returning 1 for basic types rather than asserting ?

2024-01-18 05:47 UTC, dpazj commented
> @dpazj @edward-scott @luke-shields Might be an argument for this function returning 1 for basic types rather than asserting ?

I think this makes the most sense if it is a generic function that can be applied to all iot_data_t

2024-01-18 11:13 UTC, SteveOss requested changes
In iot_data_length think still need to assert if data type MULTI or INVALID. So:

assert (data && (data->type <= IOT_DATA_MAP));

Can just set default length value to 1, so in switch statement "default: break;"

Can also just use data->type as opposed to iot_data_type in switch

Missing space before brace is unit test static functions

2024-01-18 11:23 UTC, SteveOss approved these changes
LGTM

2024-01-18 11:23 UTC, luke-shields commented
@SteveOss Change made

2024-01-18 13:23 UTC, merged