XRT-2803: add cbor decode support
IOTechSystems/iotech-c-utils pull request #332
Opened 2024-03-01 10:38 UTC by dpazj

2024-03-01 10:42 UTC, dpazj commented
@iain-anderson Not sure what to do for cbor type "tag" so currently returning null when we encounter. Any suggestions on how to handle properly?

2024-03-01 11:13 UTC, iain-anderson commented
> @iain-anderson Not sure what to do for cbor type "tag" so currently returning iot_data_null when we encounter. Any suggestions on how to handle properly - maybe we just ignore entirely?

I think the right thing is to do `cbor_tag_item (tag)` until the thing we've got isn't a tag. ie we ignore the tags but we do process the thing to which the tag has been applied

2024-03-01 11:17 UTC, iain-anderson commented on src/c/data-cbor.c
> +  switch (cbor_int_get_width (item))
Should we always allocate i64 / ui64 like what the JSON decoder does?

2024-03-01 11:45 UTC, SteveOss commented on src/c/data-cbor.c
> +  switch (cbor_int_get_width (item))
Is more compatible with JSON decoder if we do, however less correct. Potential for error is where we do something like:

uint16_t port = (uint16_t) iot_data_map_get_i64 (map, key);

This will fail if we actually have the correct type in the map as opposed to the JSON int64_t. However this form
should really be deprecated and instead should be using:

iot_data_map_get_number (map, key, IOT_DATA_UINT16, &port);

I guess my preference would be to be type correct and weed out any of the horrible casts we did to support the JSON mapping (pretty much in any JSON config handling code). I strip them out when I find them, but havn't done a systematic search and replace.

2024-03-01 12:02 UTC, iain-anderson commented on src/c/data-cbor.c
> +  switch (cbor_int_get_width (item))
OK for unsigned but there's a problem with CBOR negatives, which is that they can exceed the range of a C signed int of the same width, eg an 8-bit CBOR negative int has a range of -1..-256

2024-03-01 12:07 UTC, dpazj commented on src/c/data-cbor.c
> +  switch (cbor_int_get_width (item))
Im guessing then I should use a int16 to represent this?

2024-03-01 14:12 UTC, iain-anderson commented on src/c/data-cbor.c
> +  switch (cbor_int_get_width (item))
Yeah and I think we have to just accept that there will be values that don't fit into an int64

2024-03-04 11:14 UTC, iain-anderson commented on src/c/data-cbor.c
> +      return iot_data_alloc_i8 ((int8_t) (-cbor_get_uint8 (item)));
My reading of the spec is that these should all be `( -1 - cbor_get_uintx (item))`

2024-03-04 11:42 UTC, dpazj commented on src/c/data-cbor.c
> +      return iot_data_alloc_i8 ((int8_t) (-cbor_get_uint8 (item)));
Fixed this, however I think there may be an off by one error in the encoder as the negative int tests that use this are all failing.

2024-03-04 11:46 UTC, iain-anderson commented on src/c/data-cbor.c
> +      return iot_data_alloc_i8 ((int8_t) (-cbor_get_uint8 (item)));
Think you're right :) Can you check using https://cbor.me/ ?

2024-03-04 14:08 UTC, iain-anderson commented on src/c/data-cbor.c
> +      return iot_data_alloc_i8 ((int8_t) (-cbor_get_uint8 (item)));
Don't think the 0xFF code should be used other than to terminate indefinite strings/maps/arrays

2024-03-04 16:21 UTC, iain-anderson requested changes
Also need to add libcbor as a dependency when generating the package

2024-03-04 16:21 UTC, iain-anderson commented on src/c/data-cbor.c
> +  if (chunk_count == 0) return NULL;
The sequence `0x7F, 0xFF` decodes okay and results in an indefinite string with zero chunks - should return a zero-length string in this case

2024-03-04 16:21 UTC, iain-anderson commented on src/c/data-cbor.c
> +    char *new_data = realloc (data, data_size);
assume realloc works

2024-03-04 16:21 UTC, iain-anderson commented on src/c/data-cbor.c
> +  iot_data_t *iot_map = iot_data_alloc_map (IOT_DATA_STRING);
Maps don't have to be keyed on strings

2024-03-04 16:21 UTC, iain-anderson commented on src/c/data-cbor.c
> +    assert (false);
Don't think this should be an assertion, the calling code should detect the null return and report an error

2024-03-04 16:21 UTC, iain-anderson commented on src/c/utests/runner/runner.c
> +  cunit_data_test_init ();
undo this

2024-03-04 17:30 UTC, iain-anderson commented on src/c/data-cbor.c
> +      return iot_data_alloc_i16 (-1 - (int16_t) cbor_get_uint8 (item));
What if we do something like
```
uint8_t raw = cbor_get_uint8 (item);
return (raw < 254) ? iot_data_allow_i8 (-1 - raw) : iot_data_alloc_i16 (-1 - (int16_t)raw);
```
etc ?

2024-03-05 09:45 UTC, iain-anderson approved these changes

2024-03-05 09:47 UTC, dpazj commented on src/c/data-cbor.c
> +      return (raw <= INT64_MAX) ? iot_data_alloc_i64 (-1 - (int64_t) raw) : iot_data_alloc_i64 (-1 - (int64_t) raw);
@iain-anderson not sure how we should handle the case where the value is over the INT64_MIN - should we treat as error and return NULL or leave as is?

2024-03-05 09:48 UTC, dpazj commented on src/c/data-cbor.c
> +      return (raw <= INT64_MAX) ? iot_data_alloc_i64 (-1 - (int64_t) raw) : iot_data_alloc_i64 (-1 - (int64_t) raw);
If so I can simplify this line to iot_data_alloc_i64 (-1 - (int64_t) raw)

2024-03-05 09:57 UTC, iain-anderson commented on src/c/data-cbor.c
> +      return (raw <= INT64_MAX) ? iot_data_alloc_i64 (-1 - (int64_t) raw) : iot_data_alloc_i64 (-1 - (int64_t) raw);
We can't properly represent it, so either return NULL, iot_data_alloc_null, or allocate a float64. Think I prefer alloc_null.

2024-03-05 14:01 UTC, merged